# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d4079b54dd7d75749d35ed38fcd0c9d4c5bf50213940c7a6f16924886f3a0a202bed6cce2bb2107547f098686b1a4201ca2e019fda9acdcd0d70b3e4b7af8b05

test:
  secret_key_base: d6f8a490625fe071df4b0420de3939a0be8b9df495344ab8d920b25148e24f15edbd49435aca7d824ae5a6398f85a21913408ba8c711be57f6c025eb0cdb84c3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
